name: Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl
        curl -L https://musl.cc/aarch64-linux-musl-cross.tgz | sudo tar xz -C /usr/local

    - name: Build
      run: |
        export CC=/usr/local/aarch64-linux-musl/bin/aarch64-linux-musl-gcc
        make

    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.CODEHUB_TOKEN }}
        branch: main
