name: Build and Push aarch64-linux-musl-gcc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y curl git make musl-dev gcc

    - name: Download and extract aarch64-linux-musl-gcc
      run: |
        mkdir -p $HOME/gcc
        cd $HOME/gcc
        curl -L https://musl.cc/aarch64-linux-musl-cross.tgz | tar xzvf -
        
    - name: Build aarch64-linux-musl-gcc
      run: |
        cd $HOME/gcc
        export PATH=$HOME/gcc/bin:$PATH
        make -j$(nproc) all-target-libgcc
        
    - name: Push aarch64-linux-musl-gcc to repository
      uses: actions/upload-artifact@v2
      with:
        name: aarch64-linux-musl-gcc
        path: $HOME/gcc/bin/aarch64-linux-musl-gcc
