name: Build and push glibc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential texinfo bison flex

    - name: Download and extract glibc source
      run: wget https://ftp.gnu.org/gnu/glibc/glibc-2.33.tar.gz && tar -xzf glibc-2.33.tar.gz && cd glibc-2.33

    - name: Configure glibc
      run: ./configure --prefix=/usr/local/glibc

    - name: Build and install glibc
      run: make && sudo make install

    - name: Create archive of glibc files
      run: tar -czvf glibc.tar.gz /usr/local/glibc

    - name: Push archive to repository
      uses: actions/upload-artifact@v2
      with:
        name: glibc
        path: glibc.tar.gz
