name: Build aarch64-linux-musl-gcc

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential wget

    - name: Download and extract aarch64-linux-musl-gcc
      run: |
        wget https://musl.cc/aarch64-linux-musl-cross.tgz
        tar -xvf aarch64-linux-musl-cross.tgz

    - name: Build aarch64-linux-musl-gcc
      run: |
        cd aarch64-linux-musl-cross
        ./configure --prefix=/usr/local/aarch64-linux-musl
        make -j$(nproc)
        sudo make install

    - name: Push compiled files to repository
      uses: actions/upload-artifact@v2
      with:
        name: aarch64-linux-musl-gcc
        path: /usr/local/aarch64-linux-musl
