name: Setup docker CI
run-name: ${{ github.actor }} is testing out Node.js 🚀
on: [push]
jobs:
  ci:
    runs-on: [self-hosted, Windows, X64]
    steps:
    - uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12
    - run: |
        set -x
        docker version
        docker run --rm hello-world
